apiVersion: apps/v1
kind: Deployment
metadata:
  name: "springbootdemo"
  labels:
    app: "springbootdemo"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "springbootdemo"
  template:
    metadata:
      labels:
        app: "springbootdemo"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
