apiVersion: v1
kind: Service
metadata:
  name: "springbootdemo"
  labels:
    app: "springbootdemo"
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: "springbootdemo"
  type: {{ .Values.service.type }}
